services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sadem_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - sadem_net

  webserver:
    image: nginx:alpine
    container_name: sadem_nginx
    restart: unless-stopped
    ports:
      - "4041:80"
    volumes:
      - ./:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - sadem_net
    depends_on:
      - app

  db:
    image: postgres:15-alpine
    container_name: sadem_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: laravel
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - sadem_db_data:/var/lib/postgresql/data
    ports:
      - "54324:5432"
    networks:
      - sadem_net

networks:
  sadem_net:
    driver: bridge

volumes:
  sadem_db_data:
    driver: local
